#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  cloud:
    consul:
      host: 116.85.53.248
      port: 8500
      discovery:
        prefer-ip-address: true
zuul:
  routes:
    api-a:
      path: /hello/**
      serviceId: service-feign
    api-b:
      path: /hello2/**
      serviceId: consul-miya
management:
  security:
    enabled: false