spring:
  cloud:
    consul:
      host: 116.85.53.248
      port: 8500
      discovery:
        prefer-ip-address: true
  application:
    name: service-hello
server:
  port: 8502
management:
  security:
    enabled: false
